config/routes.rb
Rails.application.routes.draw do
  get 'places/search' => 'places#search'
  
  resources :places

  root 'places#landing_page'

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base
  has_and_belongs_to_many :places
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_and_belongs_to_many :amenities
  validates :name, :latitude, :longitude, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :prepare_for_mobile

private

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  include ActionController::Live

  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /places/search?lat=31.12923&long=64.34234234&q=amenities:1,2,3
  def search
    @places = Place.all

    respond_to do |format|
      format.html { render 'search_results'}
    end
  end

  def landing_page
    @amenities = Amenity.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :address, amenity_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  def map_url_for(place)
    if mobile_device?
      "comgooglemaps://?center=#{place.latitude},#{place.longitude}&q=#{place.latitude},#{place.longitude}&zoom=15"
    else
      "https://www.google.com/maps?z=15&q=#{place.latitude}+#{place.longitude}&ll=#{place.latitude}+#{place.longitude}"
    end

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabyPlaces</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{BabyPlaces::Application.config.maps_api_key}&libraries=places" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar">
          </span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Baby Places</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Add Place', new_place_path, class: 'btn'%></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>


  <div class="container-fluid">

    <div class="row">
      <%= yield %>
    </div>

  </div><!-- /.container -->

  <%= yield :footer_scripts %>
</body>
</html>

app/views/places/_form.html.erb
<div class="col-lg-12">
  <%= simple_form_for(@place, html: { class: 'form-horizontal' }) do |f| %>
    <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map-canvas" class="field">
      
    </div>
    <%= f.input :name%>
    <%= f.association :amenities, as: :check_boxes %>
    <%= f.input :latitude, as: :hidden %>
    <%= f.input :longitude, as: :hidden %>
    <%= f.input :address, as: :text%>

    <%= f.button :submit, class: "btn btn-lg btn-primary"%>
  <% end %>
</div>

app/views/places/edit.html.erb
<div class="col-lg-12">
  <h1 style="display: inline"><%= @place.name %></h1>

  <%= render 'form' %>

  <%= link_to 'Show', @place %> |
  <%= link_to 'Back', root_path %>

  <script type="text/javascript">
    window.Map.initializeMap({lat: <%=@place.latitude%>, lng: <%=@place.longitude%> });
  </script> 
</div>

app/views/places/landing_page.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to BabyPlaces!</h1>
    <p>What are you looking for ?</p>
    
    <p><%= link_to 'Search Nearby Places', places_search_path, class: 'btn'%></p>
  </div>
</div>

app/views/places/new.html.erb
<div class="col-lg-12">
  <h1 style="display: inline">Add New Place</h1>

  <%= render 'form' %>

  <br/>

  <span style="padding-left:15px"><%= link_to 'Back', places_path %></span>

  <script type="text/javascript">
    window.Map.initializeMap();
  </script>
</div>

app/views/places/search_results.html.erb
<div class="col-md-12">
  <div class="container">
    <% @places.each do |place| %>
      <div class="row">
        <div class="col-md-6">
          <img class="map-img" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= place.latitude %>,<%= place.longitude %>&zoom=15&size=800x150&markers=color:green%7C<%= place.latitude %>,<%= place.longitude %>">
        </div>
        <div class="col-md-4">
           <h4><%= place.name %></h4>
           <p><%= place.address %></p>
           <p><em><%= place.amenities.map{|a|a.name}.join ', ' %></em></p>
        </div>
        <div class="col-md-2">
          <span><%= link_to 'Details', place, class: 'btn btn-md btn-info' %></span>
          <span><%= link_to 'Edit', edit_place_path(place), class: 'btn btn-md btn-warning' %></span>
          <span><%= link_to 'Get Directions', map_url_for(place), class: 'btn btn-md' %></span>
        </div>
      </div>
      <br/>
    <% end %>
  </div>
</div>

app/views/places/show.html.erb
<div class="col-lg-12">
  <h1 style="display: inline"><%= @place.name %></h1>
  <%= link_to 'Get Directions', map_url_for(@place) %>

  <br/>
  <img class="map-img" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @place.latitude %>,<%= @place.longitude %>&zoom=16&size=800x200&markers=color:green%7C<%= @place.latitude %>,<%= @place.longitude %>">

  <div>
    <strong>Amenities:</strong>
    <ul>
      <% @place.amenities.each do |amenity| %>
        <li>
          <%= amenity.name %>
        </li>
      <% end %>
    </ul>
  </div>

  <div>
    <strong>Address:</strong>
    <%= @place.address %>
  </div>

  <%= link_to 'Edit', edit_place_path(@place) %> |
  <%= link_to 'Back', root_path %>
</div>